title: config
apps:
  api:
    port: integer
    privatePort: integer
    useCachingInterceptor: boolean
libs:
  common:
    governance:
      contractAddress: string
    network:
      type: string
      enum: [devnet, testnet, mainnet]
    urls:
      api: string
      gateway: string
    redis:
      host: string
      port: integer
    features:
      keepAliveAgent:
        enabled: boolean
    keepAliveTimeout:
      downstream: integer
      upstream: integer
    nativeAuth:
      maxExpirySeconds:
        type: integer
        default: 86400
      acceptedOrigins:
        type: array
        items: string
    security:
      admins:
        type: array
        items: string
        default: []
    rateLimiterSecret:
      type: string
      required: false
