/* Autogenerated code */

export interface Config {
  apps: {
    api: {
      port: number;
      privatePort: number;
      useCachingInterceptor: boolean;
    };
  };
  libs: {
    common: {
      governance: {
        contractAddress: string;
      };
      network: "devnet" | "testnet" | "mainnet";
      urls: {
        api: string;
        gateway: string;
      };
      redis: {
        host: string;
        port: number;
      };
      features: {
        keepAliveAgent: {
          enabled: boolean;
        };
      };
      keepAliveTimeout: {
        downstream: number;
        upstream: number;
      };
      nativeAuth: {
        maxExpirySeconds: number;
        acceptedOrigins: string[];
      };
      security: {
        admins: string[];
      };
      rateLimiterSecret?: string;
    };
  };
}
